version: '3.8'
services:
  web:
    working_dir: /app
    privileged: true
    #build: .
    image: python:3.9
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # 
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    entrypoint: /app/entrypoint.sh
    environment:
      - ENVIRONMENT=development
