requirements:
  - git+https://github.com/huggingface/transformers.git
  - fastapi
  - uvicorn
  - six
  - pyyaml
  - python-dotenv
  - torch 
  - accelerate
ports:
  - 8005:8000
endpoint:
  - chat
environment:
  - model=Phind/Phind-CodeLlama-34B-v2